### ISSUE TITLE
ModuleNotFoundError: No module named 'fastgedcom.family_aid'

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GatienBouyer/fastgedcom#1]
```
pip3.11 list | grep fastgedcom
fastgedcom                    0.0.3
```

```
line 1, in <module>
    from fastgedcom.family_aid import FamilyAid
ModuleNotFoundError: No module named 'fastgedcom.family_aid'
```

**Comment by VelizarVESSELINOV** [comment]
Sorry confused, by not matching the examples on GitHub and the older version on PyPI

**Comment by VelizarVESSELINOV** [comment]
Suggestions:
1. tag your code with the release version
2. post releases it will be great
 
It will be easy to follow your changes.

**Comment by GatienBouyer** [comment]
I apologize, it is my first package. And I am very happy you're contacting me and sharing interest in my project!

In version 0.0.3, I find it normal that there is no FamilyAid. It was still part of the main Gedcom class. The package was still at an early stage and I wanted to change some of the names, and the structure. Like our subject, the separation between the main class, now called Document, and the class around relatives, FamilyAid, those changes break the user code.

In the brand-new version 0.0.4, your problem should be fixed. I'll let you tell me if there is a new issue. I have passed the package from pre-alpha to alpha to highlight that package, class and method names should not change much more in the future.

**Comment by GatienBouyer** [comment]
As you advise, I tagged the version releases. And I will work for next version on a separated branch to help people who use the library and visit this repo looking for information.

**Comment by GatienBouyer** [comment]
> - Add doc with a version number
I am not sure what you're asking. I'm looking for a practical way to build documentation from code. The version of documentation produced should then match the version of the library.

**Comment by GatienBouyer** [comment]
> - Example or helper to define is a person is dead even if we are missing the date

I don't know what people are looking for. I was thinking of adding some examples but I need some use cases.

That should do what you want: (with version 0.0.4)
```python
from fastgedcom.base import is_true, Record

def is_dead(indi: Record) -> bool:
	return is_true(indi > "DEAT")
```

**Comment by GatienBouyer** [comment]
> - Ability to start the family exploration from a root

If I understand your request correctly, it is already the case. 
All root elements are accessible via the Document class (previously the Gedcom class). Such as "HEAD", individuals, families, sources, ...

```python
document["@F1@"]
# or, for the exact same thing
document.get_record("@F1@")
```

**Comment by VelizarVESSELINOV** [comment]
x

> > * Add doc with a version number
> 
> I am not sure what you're asking. I'm looking for a practical way to build documentation from code. The version of documentation produced should then match the version of the library.

https://gedcom.nickreynke.dev/gedcom/index.html (doc dedicate page, you can use different Python tools for doc)
https://pandas.pydata.org/pandas-docs/version/2.0.0/ (doc with a version number, to avoid confusion)
