### ISSUE TITLE
Few suggestions (Pythonic style, display and exception)

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GatienBouyer/fastgedcom#5]
1. `if is_true(father):` to replace it with `if father:` or `if father.empty:` like Pandas DataFrame .empty

1. `format_name(father >= "NAME")` to father.name()

1. Can we function that computes the level against one person (default):
- -1 (children's)...
- 0 (same level, siblings, cousins), 1 (parent, uncle, aunt, etc.)
- 2 (grand-parents)
- if possible relationship tag (father, mother, uncle, cousin, 2nd cousin, 3rd cousin removed...)

1. Display as graph of the family tree
 
1. When I call `get_stepsiblings` I get this error:
  ```
      106 def get_stepsiblings(self, indi: IndiRef) -> list[IndiRef]:
  --> 107 	parent_family = self.get_parent_family(self.document.level0_index[indi])
      108 	father, mother = self.get_parents(indi)
      109 	unions: list[TrueLine] = []
  
  TypeError: unhashable type: 'TrueLine'
  ```

**Comment by GatienBouyer** [comment]
I can't tell you how happy I am to see someone using something I've programmed and with whom I can interact, thank you!

**Comment by GatienBouyer** [comment]
> if is_true(father): to replace it with if father: or if father.empty: like Pandas DataFrame .empty

I like the idea. And I even know how to implement it. Not sure about the named however. I prefer `line.exist` or `line.exists` as the payload can be empty. I assume that also mean that I can remove `is_true` (an acceptable backward compatibility rumpture I hope).

**Comment by GatienBouyer** [comment]
> format_name(father >= "NAME") to father.name()

This would be handy for sure, but I don't see a convenient implementation for it.

My proposal would be to make a class derived from `TrueLine `(or `Record`, they are the same) named `IndiRecord` which would have a `name()` or `get_name()` method. As the code is procedural rather than object-oriented, I am not sure I would want that. Nevertheless, I am open to other implementation ideas and I will keep track of features that would encourage such a change.

**Comment by GatienBouyer** [comment]
>  Can we function that computes the level against one person (default):
> -   -1 (children's)...
> -    0 (same level, siblings, cousins),
> -    1 (parent, uncle, aunt, etc.)
> -    2 (grand-parents)
>  
> if possible relationship tag (father, mother, uncle, cousin, 2nd cousin, 3rd cousin removed...)

A general function to do various request. Why not! However I don't understand how your "relationship tag" works.
The way I see it is as follow:
```python
def get_relatives(indi: IndiRef, ascending_degree: int = 0, horizontal_degree: int = 0) -> list[Record]: ...

get_relatives(person, 1) -> parents
get_relatives(person, 2) -> grandparents
get_relatives(person, -1) -> children

get_relatives(person, 0, 0) -> siblings (and stepsiblings)
get_relatives(person, 0, 1) -> cousins
get_relatives(person, 0, 2) -> second cousins (cousins with a degree of two)

get_relatives(person, 1, 1) -> siblings of the parents (i.e. oncles and aunts)
get_relatives(person, 2, 1) -> siblings of the grandparents
get_relatives(person, 1, 2) -> cousins of the parents

get_relatives(person, -1, 1) -> cousins of the children (i.e. niece or nephew)
get_relatives(person, -2, 1) -> cousins of the grandchildren
get_relatives(person, -1, 2) -> second cousins of the children
```
I am not familiar with the notion of degree. My reference: https://en.wikipedia.org/wiki/Cousin
I may learn it in the hope that getting people of the 3rd degree can be easily be done using that function. I am a bit afraid of the implementation of it. I will see.

I don't rate this function as a high priority.  I am not aware of any major applications.

**Comment by GatienBouyer** [comment]
> Display as graph of the family tree

This is a visualization issue. The library is intended to remain focused on the manipulation of gedcom data.

You don't explain what kind of graph. If it doesn't require much third-party library, if any, we could put it as an example.

**Comment by GatienBouyer** [comment]
> When I call get_stepsiblings I get this error:

The function take an `IndiRef` like "@I1@" as the other methods of FamilyAid.  Still not sure on the name! lol

According to the error message, you passed the `TrueLine` of the person (or `Record`, they are the same). You will need to use the `payload` or the `tag` of the line, whichever the one holds the reference of the person.
```python
family_aid = FamilyAid(document)
me = document["@I1@"]
my_father, my_mother = family_aid.get_parents(me.tag)
my_uncles_and_aunts = family_aid.get_siblings(my_father.tag) + family_aid.get_siblings(my_mother.tag)
print([p >= "NAME" for p in my_uncles_and_aunts])
```

**Comment by GatienBouyer** [comment]
I intend to share some usage examples in the near future. Thanks again for your feedback!

**Comment by GatienBouyer** [comment]
> > if is_true(father): to replace it with if father: or if father.empty: like Pandas DataFrame .empty
> 
> I like the idea. And I even know how to implement it. Not sure about the named however. I prefer `line.exist` or `line.exists` as the payload can be empty. I assume that also mean that I can remove `is_true` (an acceptable backward compatibility rupture I hope).

Unfortunately, the Python type system doesn't support TypeGuard on self. See https://github.com/python/mypy/issues/14425. But I succeed to make it work with mypy (not with pyright unfortunately).

I let the `is_true` function as it is the intended way of doing the type check and I add my version of `exists` for what it is worth.

Note:  `if line: ...` and `bool(line)` were and will remain a correct way to do it when type-checking is disabled

**Comment by GatienBouyer** [comment]
I implemented the `get_relatives()` method we discussed. I also plan to implement a `get_with_degree()` method based on the definition of kinship degree found here https://heirbase.com/degrees_of_kinship_chart/.

**Comment by GatienBouyer** [comment]
Why haven't I thought of this before? To differentiate `TrueLine `and `FakeLine`, the boolean check is enough. With the proper overload of `__bool__`, it works with typecheckers. Same principle as for the previous `exists` attribute, but applied to the `__bool__ ` method.
